services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - reactive-backend-tier

  db:
    image: library/postgres:13-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - reactive-backend-tier
    volumes:
      - reactive-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=reactive-demo
      - POSTGRES_PASSWORD=reactive-demo

volumes:
  reactive-db:
    driver: local

networks:
  reactive-backend-tier:
    driver: bridge
