services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: library/postgres:13-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - reactive-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=reactive-demo
      - POSTGRES_PASSWORD=reactive-demo

volumes:
  reactive-db:
    driver: local
